spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

rapidapi:
  key: ${RAPID_KEY}

profile:
  host: ${PROFILE_HOST}
  port: ${PROFILE_PORT}