server:
  port: 8222
  error:
    include-message: Always

spring:
  application:
    name: mc-profile
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    mongodb:
      uri: mongodb://joety:secret@local.jtm-network.com:27017/admin
      database: test

stripe:
  pb-key: pk_test_PaeTpdrWnqKVIL9VrIZn8P9T
  secret-key: $sk_test_ypyCkIkvsRCBXxZXwQBKgKxd