spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

host:
  profile: ${PROFILE_HOST}

gcp:
  project-id: ${PROJECT_ID}
  bucket-name: ${BUCKET_NAME}